### ISSUE TITLE
implement a standard basic auth filter

### ISSUE THREAD

**Issue by doujiang24** [mosn/envoy-go-basic-auth#1]
a basic implementation:
https://github.com/doujiang24/envoy-go-filter-example/tree/master/example-basic-auth

configuration:
1. support multiple usename/password pairs
2. support valid time for a single username/password pair

tests are need.

**Comment by yizhibian** [comment]
I want to try#1. Thanks.

**Comment by spacewander** [comment]
> 2\. support valid time for a single username/password pair

Is there any usage for the expiry feature? If the users want to expire the pair, they can simply submit a new config anytime.

**Comment by spacewander** [comment]
After discussing with @doujiang24  this morning, we decide not to add valid time for now. So only "multiple usename/password pairs" is needed.
CC @yizhibian

**Comment by spacewander** [comment]
A general expiration solution would be suitable instead of implementing it in each auth plugin.

**Comment by yizhibian** [comment]
I see , I will delete that fuction.

**Comment by spacewander** [comment]
Consider solved. Thanks for @yizhibian!
